name: Deploy Cloud Run Job

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: inbound-core
  REGION: asia-northeast1
  AR_REPO: insta
  IMAGE_NAME: instagram-hashtag
  # 更新したいJob名をスペース区切りで列挙
  JOBS: "instagram-hashtag instagram-refresh"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Set project
        run: gcloud config set project $PROJECT_ID

      - name: Configure docker auth
        run: gcloud auth configure-docker $REGION-docker.pkg.dev -q

      - name: Build image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/$IMAGE_NAME:latest .

      - name: Push image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/$IMAGE_NAME:latest
      
      #- name: Update Cloud Run Jobs image
      # run: |
      #  for JOB in $JOBS; do
      #   echo "Updating job: $JOB"
      #  gcloud run jobs update "$JOB" \
      #   --image $REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/$IMAGE_NAME:latest \
      #  --region $REGION
      #    done
